jlblancoc/nanoflann

examples/pointcloud_adaptor_example.cpp
examples/pointcloud_example.cpp
examples/pointcloud_kdd_radius.cpp
examples/saveload_example.cpp
examples/vector_of_vectors_example.cpp
include/nanoflann.hpp
tests/test_main.cpp

compiled with clang 3.5 and fixed warnings wherever the came up
openend issues for the remaining warnings

fixed a lot of warnings with clang

---

include/nanoflann.hpp

Small typo.

---

examples/matrix_example.cpp
examples/pointcloud_adaptor_example.cpp
examples/pointcloud_example.cpp
examples/pointcloud_kdd_radius.cpp
examples/saveload_example.cpp
examples/vector_of_vectors_example.cpp

Currently the seed in example files was not randomized so each time we get the same value on using rand().

Randomized Seed in example files

---

examples/matrix_example.cpp
examples/pointcloud_adaptor_example.cpp
examples/pointcloud_example.cpp
examples/pointcloud_kdd_radius.cpp
examples/saveload_example.cpp
examples/vector_of_vectors_example.cpp
include/nanoflann.hpp

Example codes occur compilation error on windows 7 x86, visual studio 2013.

Fix compilation error in windows 7 x86

---

include/nanoflann.hpp

Hi @jlblancoc, this is my first try. What do you think?
If you have a code-style, can you put that into a .clang-format file in the root of your repository? That way it'd be easier for me to adhere to your style.
Please be sure to note that I removed
`inline void set_radius_and_clear( const DistanceType r )`
Can you please document KNNResultSet::addPoint()'s implementation? I'd like to be sure I got it right, and understand what you did.
Thanks!
Ben

Allow stopping search, slight cleanup

---

include/nanoflann.hpp

Changed `int i` to `size_t i` to avoid compiler warning

Changed iterator variable to suppress unsigned/signed integer warning

---

include/nanoflann.hpp

I did this change on my own clone.
It could maybe interest you.

Change specific CArray type to std::array (c++11)

---

include/nanoflann.hpp

Fix VS warning for casting int to float or double

---

examples/dynamic_pointcloud_example.cpp

I added code showing how to search for more than 1 point to the dynamic point cloud example.

Extend example for searching more than one point

---

include/nanoflann.hpp

throw exception on malloc failure

---

benchmarkTool/randomTests/CMakeLists.txt
benchmarkTool/randomTests/randomTests.py
benchmarkTool/realTests/CMakeLists.txt
benchmarkTool/realTests/realTests.py
benchmarkTool/tool.py

Just a few benchmark fixes.   
Since the original Flann cannot be compiled now, in order to check this MR, you need to replace the link in 3rdparty/CmakeLists-flann.txt with https://github.com/tkircher/flann or https://github.com/BaltashovIlia/flann.

Benchmark fixes

---

include/nanoflann.hpp

Silences compiler warning.
Closes #162

Add explicit default cctor 

---

benchmarkTool/randomTests/benchmark_nanoflann_random.cpp
benchmarkTool/realTests/benchmark_nanoflann_real.cpp
examples/KDTreeVectorOfVectorsAdaptor.h
examples/SO2_adaptor_example.cpp
examples/SO3_adaptor_example.cpp
examples/example_with_cmake/pointcloud_example.cpp
examples/example_with_pkgconfig/pointcloud_example.cpp
examples/matrix_example.cpp
examples/pointcloud_adaptor_example.cpp
examples/pointcloud_custom_metric.cpp
examples/pointcloud_example.cpp
examples/pointcloud_kdd_radius.cpp
examples/saveload_example.cpp
examples/vector_of_vectors_example.cpp
include/nanoflann.hpp
perf-tests/nanoflann/test_leaf_max_size.cpp
perf-tests/nanoflann/test_nanoflann.cpp
tests/test_main.cpp

Remove redundant calls of buildIndex()

---

include/nanoflann.hpp

also removed `sq` from some var/arg names (distsq, out_distances_sq) since they are appropriate only for L2 metric
It took me a while when adopting this library by just reading the doxygen doc for those entry points before noticing the note about the distances being squared here https://github.com/jlblancoc/nanoflann#12-c-api-reference.
I think it's nice to have this note directly in the header comment so that even sloppy users (like myself) wouldn't miss it.

doc: add note on squared distances directly to entry points (knnSearch, radiusSearch) to minimize chance of confusion

---

CMakeLists.txt
include/nanoflann.hpp

i used aggressive diagnostics of compiler and had a problem with warning -Wshadow in few lines.

fix warning -Wshadow

---

.circleci/check_style.sh
.circleci/clang_format_codebase.sh
.circleci/clang_git_format/.gitignore
.circleci/clang_git_format/LICENSE
.circleci/clang_git_format/README.md
.circleci/clang_git_format/clang_git_format/__init__.py
.circleci/clang_git_format/clang_git_format/clang_format.py
.circleci/clang_git_format/clang_git_format/config.py
.circleci/clang_git_format/clang_git_format/custom_exceptions.py
.circleci/clang_git_format/clang_git_format/repo.py
.circleci/clang_git_format/clang_git_format/utils.py
.circleci/clang_git_format/format_code.py
.circleci/clang_git_format/scripts/convert_inline_dox_comments_file.sh
.circleci/config.yml
.circleci/python_reqs.txt
.github/workflows/check-clang-format.yml
.github/workflows/ci-linux.yml
CMakeLists.txt
README.md
examples/KDTreeVectorOfVectorsAdaptor.h

Add CI with GitHub Actions

---

examples/KDTreeVectorOfVectorsAdaptor.h

Nanoflann was no longer building in our CI and this fixed our issue.

Fix was not declared in this scope

---

CHANGELOG.md
examples/examples_gui/nanoflann_gui_example_R3/CMakeLists.txt
examples/examples_gui/nanoflann_gui_example_R3/nanoflann_gui_example_R3.cpp
include/nanoflann.hpp
tests/test_main.cpp

Add RKNN searches, and more code coverage and tests

---

include/nanoflann.hpp

decrease call computeMinMax() once

middleSplit_() speed up

---

include/nanoflann.hpp

Version in header does not match tagged version

Bump version
