jlblancoc/nanoflann

include/nanoflann.hpp
The overloaded functions for int,float,double and long double are redundant. 
The function https://github.com/jlblancoc/nanoflann/blob/master/include/nanoflann.hpp#L250 is valid for all data types. Further there is no performance difference between abs() and fabs().
=> Remove redundant functions

examples/KDTreeVectorOfVectorsAdaptor.h
`KDTreeVectorOfVectorsAdaptor.h` was originally intended to work with `Eigen::VectorXd`. Changed a couple of lines to make it work with `std::vector<std::vector<double> >` as well.
Changes to `KDTreeVectorOfVectorsAdaptor.h`: 
1. `nanoflann::` added as prefix `KDTreeSingleIndexAdaptor `(line 54) 
2. `::Scalar` changed to `num_t` to work with `std::vector<std::vector<num_t> >`
Code to run an example that uses `std::vector<std::vector<double> >`:
https://gist.github.com/pinaky/741aee0bff40f7ba31c52dc41c3b90b9
You just need `nanoflann.hpp` and `KDTreeVectorOfVectorsAdaptor.h`
**TODO**: tests if this didn't break `Eigen::VectorXd`
=> Changes to KDTreeVectorOfVectorsAdaptor to get it to work with STL

include/nanoflann.hpp
In the current implementation of [worst_item](https://github.com/jlblancoc/nanoflann/blob/master/include/nanoflann.hpp#L184) module, to find the point at maximum distance from query point for a given radius, [std::max_element](https://github.com/jlblancoc/nanoflann/blob/master/include/nanoflann.hpp#L188) has been directly used on m_indices_dists. The problem is, [m_indices_dists](https://github.com/jlblancoc/nanoflann/blob/master/include/nanoflann.hpp#L149) is a vector of pair with first element being index and second element being distance. So when max_element is called it returns the maximum element with respect to index rather than the distance.
=> Bug in RadiusResultSet class

README.md
By using `{}` inside the title line, we can preserve the capitalization of `C++` and `FLANN` and `NN`.
=> Updated bibtex citation

.travis.sh
To prevent all PRs from failing the build docs job on Travis. Merge's to master will work the same.
=> Prevent attempt to publish to GitHub Pages on PRs.

examples/matrix_example.cpp, include/nanoflann.hpp
It can be infered at compile time from the matrix type.
This one changes the API, but prevents the clients from having to insert the dimensionality in the first place.
=> KDTreeEigenMatrixAdaptor no longer requires DIM specification

include/nanoflann.hpp
I didn't want to change the API, but normally I would simply strip the parameter `n` from the function signature.
=> Suppress unused variable warning on Release builds.

.gitmodules
Since the last [PR merge](https://github.com/jlblancoc/nanoflann/pull/48), it became impossible to clone recursively the project. Indeed, that would result in `fatal: No url found for submodule path '3rdparty/flann' in .gitmodules`
In order to fix that, I just added the missing `.gitmodules` file pointing to the repo and it seems that the issue is now gone.
=> Fixing submodule issue

include/nanoflann.hpp
Hi,
first of all, thank you so much for your software, it works great!
I had some problems keeping the instance KDTreeSingleIndexAdaptor around, mostly when the size of the points in the dataset change. This simple addition should make the code a little bit more "stupid proof" without any negative effect.
Cheers
=> Refresh kdtree size before building the index

include/nanoflann.hpp
Hi,
I got these compilation errors with the current version in the master branch:
```
nanoflann.hpp(1825): error: more than one instance of overloaded function "log2" matches the argument list:
function "log2(double)"
function "log2(float)"
argument types are: (const size_t)
```
The integral overloads of `log2` only exist in C++11 and not in C99 (see http://www.cplusplus.com/reference/cmath/log2/), thus triggering the error. This PR fixes the problem by using the C++ version of the function.
Best regards,
Patrick Stotko
=> Fix overload of log2

README.md
The original formulae `homebrew/science` is deprecated and moved to [`brewsci/science`](https://github.com/brewsci/homebrew-science). This commit changes all `homebrew/science` to `brewsci/science`.
=> docs: update installation guide for macOS users

include/nanoflann.hpp
Problem:
When adding points within the KDTreeSingleIndexDynamicAdaptor class, the treeIndex of removed points gets overwritten with the index of the new tree. This results in previously deleted points being restored again.
To reproduce the problem:
* Add first point
* Remove the first point
* Add second point
* Search for first point (knnsearch)
Expected: second point gets returned
Outcome: first point gets returned
The proposed change would fix this by only overwriting those points whose treeIndex is not -1, d.h. the points which were not already removed.
=> Bug fix in KDTreeSingleIndexDynamicAdaptor

examples/CMakeLists.txt
Unnecessary CMakelists code removed. This only affects the project which use Eigen (matrix_example)
=> Simplify CMakeLists for Eigen example

CMakeLists.txt, examples/CMakeLists.txt
o This should be handled by the CMAKE_INSTALL_PREFIX definition, which
is user-defined.  Setting the global cmake leads to nasty side-effects
for other cmake projects that build nanoflann as a subdirectory.
=> Avoid setting cmake global executable build path

include/nanoflann.hpp
It fails with the error: `Expected ';' at end of declaration`
=> Fix build in XCode

examples/matrix_example.cpp, include/nanoflann.hpp
Added an optional argument for the row/column layout of eigen matrices for the eigen adaptor.
Basically to fulfil this issue #37 as I want that functionality too.
=> Add optional argument for Eigen matrix layout

CMakeLists.txt
This PR installs the nanoflann.pc to /usr/share/pkgconfig, where it will
be found for all architectures, and adds the ARCH_INDEPENDENT option to
write_basic_package_version_file().
The latter requires at least CMake 3.14 to work. If this is not
acceptable for some reason, I can rewrite this with a known workaround
to set CMAKE_SIZE_OF_VOID_P to "" temporarily.
=> Install nanoflann architecture-independently

CMakeLists.txt
Prefer GNU standard locations over hard-coded ones.
Closes #129.
=> Respect GNUInstallDirs in CMake install rules

CMakeLists.txt
This is a very nice feature of CMake that was added in version 3.1.
Instead of forcing C++11 with CXX_STANDARD, which might actually
*downgrade* the compiler from a newer standard, we just tell CMake which
C++ features we need, and CMake will automatically choose the proper
standard (or complain if the compiler does not support it).
Additionally, I added the feature list as a target property, so it will
be put in the installed CMake config script and propagate to library
users. This way, CMake will automatically ensure that any project that
includes nanoflann is compiled with at least C++11.
For reference, the CMake 3.1 manual has a [list of known C++ features](https://cmake.org/cmake/help/v3.1/prop_gbl/CMAKE_CXX_KNOWN_FEATURES.html#prop_gbl:CMAKE_CXX_KNOWN_FEATURES).
=> Use target compile features instead of CXX_STANDARD

examples/saveload_example.cpp, include/nanoflann.hpp
This PR introduces C++ streams instead of the C file handles used before. The intent here is to make the library more consistent w.r.t. its programming language usage and enable specific use cases that are hard to realize portably with C file handles (e.g. in-memory streams).
Some comments in response to @jlblancoc s comments in #156:
* Using `<iosfwd>` did not work out, as it only contains forward declarations of the stream classes, so we cannot use stream methods like `read` and `write` directly in the header. My compiler only produced warnings for this, but they are rather annoying. Instead, I had to include `<istream>` + `<ostream>`.
* The Doxygen annotations already state that we save in binary format. Nothing changed about that.
This fixes #156.
=> Switch to C++ streams for index saving and loading

include/nanoflann.hpp
This fixes a couple of type conversion warnings when `AccessorType` is not the default.
=> Add missing AccessorTypes

examples/saveload_example.cpp, include/nanoflann.hpp
While benchmarking, it turned out that constructing a tree immediately
built its index. Calling loadIndex() afterwards did practically nothing.
This commit adds an enum to allow passing additional flags like
`SkipInitialBuildIndex` to allow loading a tree without the initial
index build. Greatly reduces startup time for large prebuilt trees.
=> Skip building index when loading a tree from a file

include/nanoflann.hpp, tests/test_main.cpp
The number of trees in KDTreeSingleIndexDynamicAdaptor was off by one with respect to specified maximum number of points
=> fix: avoid potential index out of bounds

include/nanoflann.hpp
In KDTreeSingleIndexDynamicAdaptor::addPoints, postponing the freeing and building of the indices until all points have been added yields a modest performance improvement.
Measured speed up ~1.15X
=> Postpone freeing and building of indices until all points have been added.

include/nanoflann.hpp
gcc <= 4.8.5 and clang <= 10.0.1 do not accept function parameter packs after a
parameter with default argument, which is perfectly valid C++ code according to
standard (8.3.6 ([dcl.fct.default])/4)
Here we remove the default and overload ctr to bypass limitation in those versions
=> fix-167: make project compile with gcc versions <= 4.8.5 and clang versions <= 10.0.1

include/nanoflann.hpp, tests/test_main.cpp
Index of tree in which point is stored was not being updated when a removed point was re-added to a KDTreeSingleIndexDynamicAdaptor.
=> fix-142: updating index of tree in which point is stored

examples/pointcloud_adaptor_example.cpp, include/nanoflann.hpp
... And removing signed to unsigned integer comparison warning
=> fix: Adding default parameter value to ctr of KDTreeSingleIndexAdaptor for backward compatibility

README.md
I spent some time trying to look for `kdd_search()`, mentioned in the README, but actually the function name is `knnSearch()`.
=> Fix confusing typo in README

examples/matrix_example.cpp, examples/vector_of_vectors_example.cpp
In some examples the original variable num_results is used for printing the nearest neighbor search results. Wouldn't it be more correct to use resultSet.size() instead?
=> examples: Use resultSet.size() in result printing loop instead of num_results

include/nanoflann.hpp
Hi, this PR contains a minor fix for the following warning:
```
nanoflann.hpp:177:19: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
: indices(0), dists(0), capacity(capacity_), count(0)
^
nullptr
```
=> fix warning -Wzero-as-null-pointer-constant

README.md
Current LinuxBrew links to a suspicious site, setting https://docs.brew.sh/Homebrew-on-Linux instead
=> Current LinuxBrew links to a suspicious site

CHANGELOG.md, README.md, examples/KDTreeVectorOfVectorsAdaptor.h, include/nanoflann.hpp, tests/test_main.cpp
#165 
When tested with valgrind --tool=helgrind tests/unit_tests, the output is like:
```
==551969== Possible data race during write of size 8 at 0x4DF8E48 by thread #4
==551969== Locks held: none
==551969==    at 0x4858B70: memset (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==551969==    by 0x4C49017: get_cached_stack (allocatestack.c:138)
==551969==    by 0x4C49017: allocate_stack (allocatestack.c:364)
==551969==    by 0x4C49017: pthread_create@@GLIBC_2.34 (pthread_create.c:647)
...
```
Then I checked [source code of glibc](https://github.com/bminor/glibc/blob/glibc-2.34/nptl/allocatestack.c#L136), and get
```cpp
memset (dtv, '\0', (dtv[-1].counter + 1) * sizeof (dtv_t));
```
at the line mentioned in helgrind. This line of code belongs to the function used to create …
=> Add concurrent tree build support

include/nanoflann.hpp
[PR 198](https://github.com/jlblancoc/nanoflann/pull/198) fails to build with g++ 9 since 
`std::atomic<unsigned int> thread_count = 0;` 
would call deleted copy constructor 
`atomic& operator=(const atomic&) = delete;` 
instead of `constexpr atomic(__integral_type __i) noexcept : __base_type(__i) { }` before g++ 11 and clang 16.
This new construction method is to use `std::atomic<unsigned int> thread_count(0u);`, which will successfully compile in my tests with g++ 4.8.5, 9, 10, 11, and 12.
=> fix: thread_count failed to construct before g++11

CHANGELOG.md, include/nanoflann.hpp
Fixes https://github.com/jlblancoc/nanoflann/issues/218
=> Improve RKNN search efficiency

scripts/nanoflannConfig.cmake.in
This is a fix for Debian bug [#1058950](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1058950). Unfortunately, both the autopkgtest  (via GTest) and my own use already have a `find_package(Threads)`, so this bug never triggered for me.
=> Look for Threads dependency in CMake config script

include/nanoflann.hpp
when using DistanceType = double;    the struct Node need 8byte aligned.
if I use a 32bit system,class PooledAllocator only can alloc 4byte aligned memory.it cause low-performance mem access.
=> fix poll-allocator alignment problem

CMakeLists.txt, include/nanoflann.hpp
Dear nanoflann devs
here are two small fixes for 
- disable uninstall target is nanoflann is included in a master project
- fix compilation in c++20, cstdint needs to be included
=> c++20 and cmake fixes

README.md, include/nanoflann.hpp
Hello. I used nanoflann in my project and got a linker error because of pthreads usage (`std::async`). Since I don't use parallel construction and don't want to link my code with pthreads, I've just removed these calls from the library. I think that it might be convenient for others to do the same by just adding a define before including the header, so I made this PR.
I was thinking about adding the possibility to disable multi-threading to CMake, but I'm not an expert on it. If you think that it is necessary, I'll figure it out and add it to the PR.
Also, I've included in the readme all the ifdefs I found in the header.
=> Add ifdef to disable pthreads usage

include/nanoflann.hpp
PR adds `n_thread_build` argument in `KDTreeEigenMatrixAdaptor` and passes it to the SingleIndexAdaptor which will address https://github.com/jlblancoc/nanoflann/issues/209 .
=> Add multiple thread kdtree build support for KDTreeEigenMatrixAdaptor

include/nanoflann.hpp, tests/test_main.cpp
While https://github.com/jlblancoc/nanoflann/pull/220 decreases amount of `middleSplit_` calls, it also prevents finding correct `min_elem` and `max_elem` when 	`max_span == 0` and `span == 0`. What leads to wrong `cutval` calculation and out of range reads at `divideTree`.
The issue can be observed with the unit test executed under valgrind.
=> Fix middleSplit_ for same points

include/nanoflann.hpp
This PR removed an `fprintf(stderr, ...)`, which seems accidentally left in, and also unnecessary.
Some projects have a hard requirement that all printing must go through overridable interfaces instead of writing directly to stdio/stderr. For example, CRAN would reject packages that use stderr directly.
While we could patch this out on our side (in igraph), it seemed appropriate to submit this change upstream. Let me know if it is acceptable.
=> do not write to stderr

include/nanoflann.hpp
Fixes #264.
This PR changes the default `IndexType` for _metric adaptor classes only_ to `size_t`. I don't see a reason for this to be `uint32_t`, as indices get converted back and forth between `size_t` and `uint32_t` in various codepaths anyway. For example, `kdtree_get_pt()` is typically defined with `size_t` anyway.
This PR _does NOT_ change the default `IndexType` to `size_t` in `KDTreeBaseClass` and its derived classes, as this would affect the size of the required storage, and I'm not sure if you'd want to do this. However, customizing the `IndexType` in those classes is easier, and need to be done in a single place only.
=> fix: use size_t as the default IndexType in metric adaptor classes
